DROP TABLE IF EXISTS INGREDIENTS;
DROP TABLE IF EXISTS UNITS_OF_MEASURE;
DROP TABLE IF EXISTS MEASUREMENT_SYSTEM;

CREATE TABLE IF NOT EXISTS MEASUREMENT_SYSTEM(
    SYS_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (SYS_ID)
  );

CREATE TABLE IF NOT EXISTS UNITS_OF_MEASURE(
  UOM_ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  SYS_ID BIGINT NOT NULL,
  PRIMARY KEY (UOM_ID),
  FOREIGN  KEY (SYS_ID) REFERENCES MEASUREMENT_SYSTEM(SYS_ID)
);

CREATE TABLE IF NOT EXISTS INGREDIENTS(
  ING_ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  UOM_ID BIGINT NOT NULL,
  PRIMARY KEY (ING_ID),
  FOREIGN KEY (UOM_ID) REFERENCES UNITS_OF_MEASURE(UOM_ID)
);
